### ISSUE TITLE
Zonotope polygone method returns duplicate points

### ISSUE THREAD

**Issue by HendrikRoehm** [TUMcps/CORA#1]
# Reproduction
instantiate any zontope Z. Then use `polygon(Z)`.
you should see that the two middle points are always the same. This results in unnecessary warnings, such as by using `polyshape(polygon(Z)')`

# Fix
In zonotope/polygon.m, change line 71-72 to:
```
p = [p(1,:),p(1,end)+p(1,1)-p(1,2:end);...
    p(2,:),p(2,end)+p(2,1)-p(2,2:end)];
```

**Comment by TUMcps** [comment]
Thank you for reporting this issue, that was indeed a small bug. We fixed it in commit 67127d5
