### ISSUE TITLE
zonotope 'isIntersecting' 

### ISSUE THREAD

**Issue by ghost** [TUMcps/CORA#10]
% Cora release 2020. Matlab 2019b. Windows 10.
zono1 = zonotope([0.7,1, -0.2, 0.5;1,1, 0.4, 0.2]);
zono2 = zonotope([1.5,0.7,0.1,0.9,0.2;1.0,-0.1,-0.1,-0.9,-0.1]);
isIntersecting(zono1, zono2)
% ans = logical 0. But It is wrong.
% In fact, two zonotopes does intersect. Plot them to check

**Comment by wetzlingerm** [comment]
We have tested the given example on Linux/Windows10 using Matlab2017b/2018b|2020a and could not reproduce the error, as we correctly obtained "true" each time. We suspect the reason might be the underlying built-in function linprog which to our knowledge has caused some issues in 2019b. Is there any way you could check if another Matlab version produces the wrong result as well?

**Comment by hitchaj** [comment]
Thank you for apply. I test the code using Matlab 2018b on the same PC. It works properly.
