### ISSUE TITLE
'split' conflicts with the split function for char arrays in MATLAB

### ISSUE THREAD

**Issue by stefanbliu** [TUMcps/CORA#11]
When calling 'split' for char arrays in MATLAB, '/global/functions/globOptimization/split.m' is invoked instead. Please avoid same function names

**Comment by wetzlingerm** [comment]
This issue has been resolved in the [last commit](https://github.com/TUMcps/CORA/commit/adcdd05d98530f7e6e7a8589384c1cba9e1d2207), where the wrongly called "split" function was deleted. Sorry for the delay in this matter.
