### ISSUE TITLE
Bug in linearSysDT concerning Output

### ISSUE THREAD

**Issue by stefanbliu** [TUMcps/CORA#13]
the output equation of a linearSysDT is y[i] = C*x[i] + D*u[i], i.e., the indices of x and u are the same

The current implementation of @linearSysDT/reach.m in line 66, however, results in y[i-1] = C*x[i] + D*u[i-1], i.e., the indices of x and u are different.

**Comment by wetzlingerm** [comment]
Thank you for catching this error! We have corrected it in the [last commit](https://github.com/TUMcps/CORA/commit/08e56f99111a70f3e6d218426998f80640e39f89).
