### ISSUE TITLE
Bug in mergeTransitionSets concerning returned variable

### ISSUE THREAD

**Issue by SMS-Maxi** [TUMcps/CORA#14]
The returned variable "res" in mergeTransitionSets is not initialized outside the for-loop in line 48 which is based on the length of the transition sets. If, at one point within execution, all components reach states which have no transitions, "res" is never initialized which leads to a run-time error.

**Comment by TUMcps** [comment]
Thank your for reporting this issue! We fixed it in commit bef0e0e.

**Comment by SMS-Maxi** [comment]
Thank you for the quick response, however the bug then propagates to potInt.m, since the returned empty cell array is dot-indexed for its attribute "guard" in line 58 which it of course doesn't have.

**Comment by TUMcps** [comment]
I tried to reproduce the issue with a dummy system but for me it runs through. Can you maybe set me your code to niklas.kochdumper@tum.de so that I can take a look? Thank you!
