### ISSUE TITLE
Repository very big due to manuals

### ISSUE THREAD

**Issue by HendrikRoehm** [TUMcps/CORA#2]
When you download the cora repository, its size is around 30MB. This big size is mostly from the manuals. As every update increases the size of the repository heavily (pdf = binary file), I would recommend splitting the repo into two:
1. code repo with matlab source code.
2. docu repo with manuals as well as the source code of the manual.
With that structure, other people can work on the manual in a structured way and the size of the sourcecode repo can be kept low.

I would be happy to hear your thoughts.

**Comment by toladnertum** [comment]
The manual is no longer part of the repository.
