### ISSUE TITLE
polytope method seems to have cyclic definition

### ISSUE THREAD

**Issue by SergeiSa** [TUMcps/CORA#20]
The following code throws an error for me:

`Z = zonotope(zeros(2, 1), randn(2, 5));`
`V = Z.polytope()`

It seems that after going to the line 193 here https://github.com/TUMcps/CORA/blob/master/contSet/%40zonotope/polytope.m, the execution halts at the line 73 here https://github.com/TUMcps/CORA/blob/master/contSet/%40mptPolytope/mptPolytope.m, trying to call the same polytope.m one more time, but now with incorrect parameters. Trying to force it to call this guy https://github.com/TUMcps/CORA/blob/master/contSet/%40mptPolytope/polytope.m does not fix the issue.

--------------------------------------
error message:

Check for missing argument or incorrect argument data type in call to function 'mptPolytope_polytope'.

Error in mptPolytope (line 82)
                obj.P=mptPolytope_polytope(varargin{1},varargin{2});

Error in zonotope/polytope (line 193)
    P = mptPolytope(C,d);

Error in try1 (line 21)
V = Z.polytope()

**Comment by wetzlingerm** [comment]
Can you confirm that the mpt toolbox is installed as specified in the manual in section 1.3?

**Comment by SergeiSa** [comment]
MPT not being in the path was indeed the problem, my apologies.
