### ISSUE TITLE
Can not plot linear discrete systems over time.

### ISSUE THREAD

**Issue by SunandanAdhikary** [TUMcps/CORA#21]
I am trying to plot the flowpipe over time for a discrete linear system. But it seems the `plotOverTime` and `plotAllOverTime`, both are using `timeInterval` field in a `reachset` object nad because the `reachSet` objects for a `linearSysDT` type objects do not contain `timeInterval` field. So I am facing error whenever trying to plot the `reachsets` over time. Am I missing something here? Or there is some issue regarding this? Please help.
```
plotOverTime(R,[1 2],'FaceColor',[.8 .8 .8],'EdgeColor','b');

```
> Dot indexing is not supported for variables of
> this type.
> 
> Error in reachSet/plotOverTime (line 83)
>        for j =
>        1:length(R(i,1).timeInterval.set)
```

```

**Comment by wetzlingerm** [comment]
Thank you for raising this issue! You are correct that discrete-time systems were not supported by the plot over time functions. This has been corrected in commit [168b66d](https://github.com/TUMcps/CORA/commit/168b66d2f5b9cfb6b4147e8464163aab7d275c41).
