### ISSUE TITLE
Issue in checking interval specification

### ISSUE THREAD

**Issue by SunandanAdhikary** [TUMcps/CORA#22]
I was facing the following error from `reach()` while trying to check a `safeSet` specification that I made using interval objects.

> Check for missing argument or incorrect argument data
> type in call to function 'polytope'.
> 
> Error in mptPolytope (line 73)
>                 obj.P=polytope(varargin{1},varargin{2});
> 
> Error in interval/mptPolytope (line 41)
> poly = mptPolytope(C,d);
> 
> Error in interval/in (line 53)
>     res = in(mptPolytope(obj1),obj2);
> 
> Error in specification/check>checkSafeSet (line 88)
>         res = in(set,S);
> 
> Error in specification/check (line 43)
>                 res = checkSafeSet(obj(i,1).set,S);
> 
> Error in linearSysDT/reach (line 87)
>             if ~check(spec,Rout{i})
> 
> Error in reachabilityAnalysis (line 81)
> [R,res] = reach(sys,params,options,spec);

Am I missing something here?
If not entirely wrong, I am guessing this happens because the mptPolytope function under interval set representation takes only an interval object as input. But the polytope function under interval on the other hand converts the input interval objects into a generic polytope-like representation and then calls mptPolytope function internally with this object (which does not take polytope type input but interval type objects as input), which might cause this error. 
The following sample code from CORA 2020 manual also throws a similar error.
```
% set S (intersection)
S1 = mptPolytope(...
[-1 -1;0 -1;0 1;1 1], ...
[-0.5; 0; 2; 2.5]);
S2 = mptPolytope(...
[-1 -1;0 -1;0 1;1 1], ...
[2.5; 2; 0; -0.5]);
S = S1 & S2;
% check if set is empty
res = isempty(S)
```

> Check for missing argument or incorrect argument data
> type in call to function 'polytope'.
> 
> Error in mptPolytope (line 73)
>                 obj.P=polytope(varargin{1},varargin{2});

Please guide. Thank you.

**Comment by wetzlingerm** [comment]
Please confirm that you have installed the MPT toolbox as specified in Sec. 1.3 of the CORA manual. If this is not the case, please install said toolbox, rerun both examples and notify us below if you still encounter the same issue.

**Comment by SunandanAdhikary** [comment]
You are right. My mpt toolbox path was not added.in Matlab search path. Now both the examples are running perfectly. Thank you.
