### ISSUE TITLE
reduce for polyZonotope

### ISSUE THREAD

**Issue by Cfather** [TUMcps/CORA#24]
reduce method in polyZonotope

line 37: N = size(pZ.G,1);

Is N here the dimension of the polynomial zonotope? I found some cases in my program that pZ.G might be empty and N becomes 0 incorrectly. Maybe using the center of the polynomial zonotope (N = length(pZ.c);) might be more reasonable and robust?

**Comment by wetzlingerm** [comment]
You are correct, N represents the dimension of the space, in which the polynomial zonotope is defined. Your suggestion is also what we used in the polyZonotope/dim.m function, which should also have been used in this case. Commit [77d87aa](https://github.com/TUMcps/CORA/commit/77d87aa533b7495f69edf71a0ba22e1e6e339f0b) takes care of that.
