### ISSUE TITLE
in(zonotope,point) not working correctly

### ISSUE THREAD

**Issue by skousik** [TUMcps/CORA#26]
The following code in CORA 2020 is returning `false` instead of `true`:
`Z = zonotope([zeros(2,1),rand(2,5)])`
`in(Z,zeros(2,1))`

However, this works correctly:
`in(Z,zonotope(zeros(2,1)))`

**Comment by wetzlingerm** [comment]
Hi,
I tried to replicate the error by checking a few thousand cases as you defined them. However, all of those containment checks were successful. Can you provide me with a specific case (generator matrix) where the wrong result is returned?
We will release a new version in the upcoming weeks, where containsPoint.m and in.m are unified. I will specifically consider this case to ensure correct functionality.

**Comment by skousik** [comment]
Thanks for checking it out! I did some further exploration and discovered that having MOSEK on my MATLAB path is causing the issue. It seems to be that MOSEK is changing the version of "linprog" that MATLAB uses.

Apologies for the confusion! If I find anything further, I'll post more comments here.
