### ISSUE TITLE
@interval/isIntersecting

### ISSUE THREAD

**Issue by haloinca** [TUMcps/CORA#27]
Run the following code:

int1 = interval([-1.4897; -0.3403], [ -0.6545; 0.3403]);
int2 = interval([-1.5; -0.1], [-0.5; 0.1]);
isIntersecting(int1, int2)

I get:
>> isIntersecting(int1, int2)
ans =
     0

However, as we know, the two intervals are intersected. Plot them we will see.

plot(int1); hold on; plot(int2, [1,2], 'r');

PS. Thinkpad E480, Windows 10, Matlab R2020b, Cora2020.

**Comment by wetzlingerm** [comment]
Thank you for finding this bug, we fixed it in the [last commit](https://github.com/TUMcps/CORA/commit/145d40b33d25ccde2b70c5d3f3c0c26a1ac60873).
