### ISSUE TITLE
Error in Jacobian evaluation for non-linear parameter system

### ISSUE THREAD

**Issue by ChitraDangwal** [TUMcps/CORA#29]
In my model I am using "nonlinParamSys" to compute the reachability of my uncertain parameter system.

My model with uncertain parameter is:

dx(1,1)= u(1)*p(3) + (x(2) - x(1)).*p(1).*p(3) ;
dx(2,1)= (28 - x(2))*p(2).*p(4) - (x(2) - x(1))*p(1).*p(4) ;
 

The error is I am getting is shown in the attached figure:
![Error_CORA](https://user-images.githubusercontent.com/65459163/125123688-d5724f80-e0ab-11eb-9332-b24c2193c374.PNG)

I think the error might be due to inaccurate computation of Jacobians, as the Jocabians files created have all 0 elements. 

How can I fix it?

**Comment by zhao-mz** [comment]
I have encountered similar errors. Have you solved this problem?

**Comment by TUMcps** [comment]
Sorry for the (very) late reply.

Please try to initialize the system with `nonlinParamSys(@ABC, 'varParam')`.
The computed Jacobian should then be in the file `jacobian_freeParam_ABC.m`

Can you double-check if this error still occurs with the latest version of CORA?
If so, we would appreciate it if you could provide your entire script file that eventually leads to this error.
