### ISSUE TITLE
add 'real' assumption to symbolic variable declaration in symVariable.m

### ISSUE THREAD

**Issue by Cfather** [TUMcps/CORA#30]
I've met this issue several times in CORA 2020. symVariable.m doesn't add 'real' assumption when declaring a matlab 'sym' variable. So when running derivatives.m to get high order derivatives, the matlab symbolic toolbox will automatically generate stuff like 'conj', which is super unfriendly to your interval class, when you try to use interval arithmetic to bound high order error. I wonder since the states in your applications mostly are real numbers, maybe you can add this 'real' assumption in the symVariable.m, so that I don't have to manually remove 'conj' every time.

**Comment by wetzlingerm** [comment]
In principal, I agree with your recommendation as our algorithms are only designed for real-valued functions.

Just for clarification, could you provide me with an example function where this occurs? The functions we currently have do not yield the mentioned generation of 'conj'.

**Comment by Cfather** [comment]
Sorry, I don't have an easy example right now.

We used a complex dynamics function which calls some subfunctions. The symbolic expression could be really complex.
