### ISSUE TITLE
`reachInner` algorithm example: problem with the `mptPolytope` contructor

### ISSUE THREAD

**Issue by dfcaporale** [TUMcps/CORA#36]
Hi, 

My name is Daniel, and I am taking my first steps heading for using the `reachInner` algorithm from your package. Trying to run the example from Sec. 4.1.2 from the CORA Manual, I got stuck with an issue. After debugging the code a little bit, I noticed that the problem is in the call to the `mptPolytope` constructor (in [this line](https://github.com/TUMcps/CORA/blob/53b4d052ce29f8a638c537fcec32230016ce07d6/contSet/%40mptPolytope/mptPolytope.m#L73)).

Here is the stack trace:

```Matlab
>> C = [1 0 -1 0 1; 0 1 0 -1 1]';
>> d = [3; 2; 3; 2; 1];
>> poly = mptPolytope(C,d);
Undefined function 'polytope' for input arguments of type 'double'.

Error in mptPolytope (line 73)
                obj.P=polytope(varargin{1},varargin{2});
```

Am I doing something wrong? 

Thanks in advance, and congratulations on your code!

**Comment by wetzlingerm** [comment]
Hi Daniel,
Thanks for your kind words!

Did you install the mpt toolbox as explained in Section 1.3 of the CORA manual?

**Comment by dfcaporale** [comment]
Hi @wetzlingerm,

You are right. I'd previously installed the required packages manually and added the paths to MATLAB, but something else needed to be set appropriately.

Now it's working perfectly. This time I did it with the script `install_mpt3.m` and tested with `test_requiredToolboxes`, and everything is fine.

Thank you so much for your quick reply!
