### ISSUE TITLE
Inner-approximation for `linParamSys`

### ISSUE THREAD

**Issue by dfcaporale** [TUMcps/CORA#37]
Hi,

I'm trying to calculate the inner approximation of the solution of a `linParamSys` problem (an interval matrix). Unfortunately, if I'm right, the `reachInner` operation is not supported for this system.

I wanted to ask you if there is any suggestion for working out such an issue.

Many thanks for considering my request,

Daniel

**Comment by wetzlingerm** [comment]
Hi Daniel,

Sorry for missing this! You are right, we currently have no algorithm dedicated specifically to computing inner-approximations of reachable sets for systems of the class `linParamSys`. However, you can extract a set of linear systems from the linear parametric system by fixing the parameter values (e.g., to some extreme values) and then compute inner-approximations using the `reachInner` function from `linearSys`. The union of those inner-approximations also constitutes an inner-approximation for the linear parametric system.

Best regards,
Mark
