### ISSUE TITLE
Issues Auxilary function removeIndepGens(cPZ) in minkdiff for calss conPolyZono

### ISSUE THREAD

**Issue by GillesDel** [TUMcps/CORA#39]
Hello, 

When removing indepent generators to depedent ones for the minkswoksi difference of constrained polynomial zonotopes, the constrained matrix A is keep the same size while transferring independant generators as dependant one. A size should be updated to the new dependant generators size : 
(Auxilary function removeIndepGens(cPZ) in minkdiff for class conPolyZono, line 122-124)

from:

       cPZ = conPolyZono(cPZ.c,[cPZ.G,cPZ.Grest], ...
                          blkdiag(cPZ.expMat,E), cPZ.A, cPZ.b, ...
                          blkdiag(cPZ.expMat_,E),[],id);
to: 

       cPZ = conPolyZono(cPZ.c,[cPZ.G,cPZ.Grest], ...
                          blkdiag(cPZ.expMat,E), [cPZ.A zeros(size(cPZ.Grest))], cPZ.b, ...
                          blkdiag(cPZ.expMat_,E),[],id);

**Comment by wetzlingerm** [comment]
Thank you for finding this bug and sorry for the delayed response! We will incorporate the fix into the next release version v2022.1.1.
