### ISSUE TITLE
Computing reachable sets for one dimensional linear dynamical systems

### ISSUE THREAD

**Issue by GuoZhongYi-Student** [TUMcps/CORA#50]
Recently I need to solve the reachable set of a one dimensional linear dynamical system, but when I set the matrix to one dimensional, the generated set is of zonotope type and one dimensional sets cannot be represented using zonotope type. I don't know how to solve the reachable set of a one dimensional linear dynamical system, can you give some suggestions.

```
Wrong value for the first input argument.
  The right value: zonotope
  Type 'help zonotope\plot' for more information.

error zonotope/plot>aux_parseInput
    inputArgsCheck({{Z,'att','zonotope'};

error zonotope/plot
[Z,dims,NVpairs] = aux_parseInput(Z,varargin{:});

error test
plot(a,b);
```

**Comment by TUMcps** [comment]
Thank you for reaching out to us.

The error seems to occur when you try to plot your zonotope.
CORA allows the initialization and plotting of one-dimensional sets represented as zonotopes. 
For example:
```
Z = zonotope(1,[1,2]);
plot(Z,1); % plot first dimension on x-axis
```

Can you send us the problematic zonotope (a) and the specified dimensions (b) of your plotting call such that we can look into it?
```
plot(a,b);
```

Also, make sure you have the latest version of CORA (v2024.1.5), as we continuously update CORA.
You can check the current version by typing `CORAVERSION` in the Matlab command window.

**Comment by GuoZhongYi-Student** [comment]
Thanks for the quick reply, I think I have solved the problem.  I had hoped to solve for the reachable set of a 1D dynamical system, but I didn't find a solution for the 1D system before. Now I am able to get the corresponding reachable set by the method you described, my dynamical system can be expressed as $\dot x = x +u,$ ${x_0} = 2,$ $u \in \left[ { - 1,1} \right]$
and my code is
```
% system dynamics
sys = linearSys(1,1,0);
% parameter
params.tFinal = 5;
params.R0 = zonotope(interval(2,2));
params.U = interval(-1,1);
% reachability settings
options.timeStep = 0.05;
options.zonotopeOrder = 10;
options.taylorTerms = 5;
% reachability analysis
R = reach(sys,params,options);
time=R.timePoint.time();
set=R.timePoint.set();

plot(set{2},1)
```
where set{2},1 is the reachable set at the next moment.

**Comment by TUMcps** [comment]
Glad to hear. Let us know if you have any further questions.

**Comment by GuoZhongYi-Student** [comment]
Thank you, I will use CORA to follow up in the direction of reachable sets!
