### ISSUE TITLE
function Removed in MATLAB Package

### ISSUE THREAD

**Issue by XiaoLiSean** [TUMcps/CORA#52]
Hi, 

I used the previous version (2022) on MATLAB and lately switched to the latest version that was updated this year. And I noticed some functions, e.g., /contSet/@zonotope/sampleBox.m, are removed in the new packages. My previous development was based on some of the removed functions. I would much appreciate it if you could point me to the alternative functions or possibly consider adding the deleted functions back.

Thanks,

**Comment by toladnertum** [comment]
Hi, 

This function was merged with `zonotope/randPoint` in v2024.1.2. 
Here is the updated code:

```
Z = zonotope([1;1], [1 1; 0 1]);
points = Z.randPoint(500,'uniform');

figure; hold on;
plot(Z,1:2);
plot(points(1,:), points(2,:), '.k')
```

Best,
Tobias
