### ISSUE TITLE
Potential use of wrong matrix in zonotope under-approximation method

### ISSUE THREAD

**Issue by ddlmcp** [TUMcps/CORA#55]
https://github.com/TUMcps/CORA/blob/af978bed1f2c51c5811588e585935bdd7a5bba4f/contSet/%40zonotope/reduceUnderApprox.m#L217

In the line above, wasn't the "G" matrix, instead of "G_", meant to be used? I'm comparing that to what is described in Theorem 3.2 of "Adaptive parameter tuning for reachability analysis of nonlinear systems", referenced in this same function. Apologies if I'm misinterpreting something, but I thought it was worth noting here in case it is indeed a typo.

Regards

**Comment by wetzlingerm** [comment]
Thank you for this bug report!

There was indeed a mistake in the computation of the Hausdorff distance. We have fixed that and renamed the variables in that specific part to match the symbolic formulas from the reference exactly. The fix will be integrated into our next version, which will be released next week.
