### ISSUE TITLE
powerSystem2cora not working

### ISSUE THREAD

**Issue by tlogemann** [TUMcps/CORA#56]
Hello,

i am using MATLAB R2024a with the latest CORA release 2024.4.0 and the respective toolboxes installed.

When I am executing e.g. `examples/contDynamics/nonlinDASys/example_nonlinearDA_reach_04_powerSystem_14bus` it throws the following error:

```
Error using sym/privsubsasgn (line 1170)
Unable to perform assignment because the indices on the left side are not compatible with the size of the
right side.

Error in indexing (line 1025)
                C = privsubsasgn(L,R,inds{:});

Error in symPowerVariables (line 112)
V(NoB.total + 1 : NoB.total + NoB.input, 1) = u(NoB.generator + 1 : NoB.generator + NoB.input, 1); %external voltages

Error in powerSystem2cora (line 53)
[powVariables, NrOf] = symPowerVariables(scenario);

Error in example_nonlinearDA_reach_04_powerSystem_14bus (line 54)
    powerSystem2cora('IEEE14');
```

Is this a bug or can you hint me, what I am doing wrong?

**Comment by toladnertum** [comment]
Dear @tlogemann,

CORA is primarily tested on R2023b and it seems like something broke with R2024a.
We will prepare a fix for that in the next release of CORA.

In the meantime, is it feasible for you to switch to R2023b?
I just tested the example there and it works fine.

**Comment by tlogemann** [comment]
Yes, I can switch to R2023b and it also works fine for me.

Thank you!
