### ISSUE TITLE
Invalid Example Files

### ISSUE THREAD

**Issue by Gu18-cps** [TUMcps/CORA#60]
Hello, I'm trying to run the examples for Nonlinear Differential-Algebraic continuous examples (as I am working on a power project and I'm trying to debug why my own case is running into issues at the linearization step). But the examples for 14-bus and 30-bus (examples 4-6) are claiming the .mat files are invalid as follows:

Error using load
Unable to read MAT-file D:\Research - Controls\CORA\models\powerSystems\IEEE14.mat. Not a binary MAT-file. Try load -ASCII to read as
text.

Error in powerSystem2cora (line 47)
scenario = load(filename);

Error in example_nonlinearDA_reach_04_powerSystem_14bus (line 54)
    powerSystem2cora('IEEE14');
    
   Is there some start-up code needed to generate the correct .mat files? The files are clearly in the correct spot as taken from github, but I don't know if the files needed to be modified somehow.

**Comment by toladnertum** [comment]
Dear @Gu18-cps,

This might be due to us switching over to git lfs (large file storage) for binary files.
Make sure you have set up git lfs properly and maybe reclone the repository if necessary.
Hope that helps!

Best,
Tobias
