### ISSUE TITLE
"runTestSuite" problem

### ISSUE THREAD

**Issue by ASCShi** [TUMcps/CORA#61]
Hello, I sincerely request your help. When I ran the "runTestSuite" file for CORA standard suite testing again, a small portion of the 1003 tests encountered the following issues. I don't know where the problem is。
The function 'matrix' corresponding to the input parameter of type 'double' is not defined (thrown in models\auxiliary\NARX2\jacobian_NARX2.m, line 3)

**Comment by toladnertum** [comment]
Dear @ASCShi, 

Thank you for reaching out. Did you make sure that all required toolboxes are installed (run `test_requiredToolboxes`)? 
Also, can you run one test that fails and post the entire error stack?

Best,
Tobias

**Comment by toladnertum** [comment]
You said that `runTestSuite` shows you that some tests fail. Can you pick one of these tests and run it in the command window? Then, you can post the entire stack trace that you obtain in the command window here.

**Comment by ASCShi** [comment]
![屏幕截图 2024-11-13 174248](https://github.com/user-attachments/assets/859bf181-c9d4-473b-92fc-84a0951b897c)
![屏幕截图 2024-11-13 174334](https://github.com/user-attachments/assets/1a37a1a1-0c10-4943-9fc7-620e4b9a7edb)
Thank you for your reply. We have selected two representative failure cases with error messages as shown in the figure.

**Comment by ASCShi** [comment]
Sorry, we didn't pay attention to the language switch. Here is the latest error message interface.
![image](https://github.com/user-attachments/assets/0fbfb74e-0986-49b8-bc24-d8f6a19ff506)

**Comment by ASCShi** [comment]
![image](https://github.com/user-attachments/assets/7538c14d-e72e-4c94-ab3c-eea972ce28ad)
This is the typical failed test we encountered.

**Comment by toladnertum** [comment]
Just to be sure, you are using the latest CORA version, right? (type `CORAVERSION` in the command window)

**Comment by ASCShi** [comment]
![1731493957927](https://github.com/user-attachments/assets/5f05adfe-d8e6-4679-9421-72b022974799)
We are using this version.

**Comment by ASCShi** [comment]
Thank you very much for your help. We have now adopted the latest version 02, and the previous issue has been resolved. Now, only this type of error appears.
![屏幕截图 2024-11-13 185018](https://github.com/user-attachments/assets/6ab5da9e-1107-45e2-aba1-e387d8479f18)
![屏幕截图 2024-11-13 184957](https://github.com/user-attachments/assets/3ba0a2f7-f270-4195-822e-ee8c09cbd012)
![屏幕截图 2024-11-13 184934](https://github.com/user-attachments/assets/252b5dea-e4f9-4f30-8014-dac3be0a5c89)

**Comment by toladnertum** [comment]
I have never seen this error. The failing tests are very simple tests without specific CORA stuff, which migh indicate that there is somehting wrong with the setup of your matlab installation. Could you show me the stacktrace of `test_withinTol`?

**Comment by ASCShi** [comment]
![image](https://github.com/user-attachments/assets/4c309fc2-eb8d-453a-80ff-2b65c02a4fda)
Very willing to serve, this is incorrect detailed information.

**Comment by toladnertum** [comment]
Can you set a breakpoint in CORAerror.m (`open CORAerror`) at line 575 and give me the content of the variables `filename`, `fileSepAfterCORA`, and `classname`?

**Comment by ASCShi** [comment]
I don't understand what you mean. Do you want to continue running runTestSuite after setting a breakpoint on CORAerror. m, or do you want to run CORAerror. m itself. Besides, I don't quite understand the meaning of the latter half of your sentence.

**Comment by toladnertum** [comment]
Please re-run `test_withinTol` and set a breakpoint in `CORAerror`. There, the variables described above are available.

**Comment by ASCShi** [comment]
Okay, thank you very much. The specific content is shown in the picture.
![1731504907954](https://github.com/user-attachments/assets/75dbf53e-499a-460a-b861-4f9908c0b87e)
![1731504935499](https://github.com/user-attachments/assets/5730f429-29b4-4cb7-b07f-7b1b901509c7)

**Comment by toladnertum** [comment]
Thanks, it looks like there is an issue with the dots in the path to CORA: `F:/CORA2025.02/CORA-2025.0.2`.


Either get rid of the dots in or change line 549 in CORAerror

    dotPos = strfind(st(errIdx).file,'.');

to

    dotPos = strfind(st(errIdx).file,'.');
    dotPos = dotPos(end); % in case multiple dots appear within the path

Hope that fixes it.
We add this bugfix to a future version of CORA.

**Comment by ASCShi** [comment]
Thank you very much. The issue has been largely resolved, and we have made changes to line 549 in CORAerror. But I also want to ask, what does the first method get rid of the dots mean and and how does it operate specifically.

**Comment by toladnertum** [comment]
In your path `F:/CORA2025.02/CORA-2025.0.2`, replace the dots with e.g. underscores: `F:/CORA2025_02/CORA-2025_0_2`. Then, there is only one dot in the path to any file within CORA (the one before the extension: `F:/CORA2025_02/CORA-2025_0_2/**/*.m`) and the code does not fail anymore.

Is there any other help you need?

**Comment by ASCShi** [comment]
Thank you very much, there are no other problems.
