### ISSUE TITLE
Cannot run Van Der Pol Example

### ISSUE THREAD

**Issue by Cfather** [TUMcps/CORA#8]
Undefined function 'polytope' for input arguments of type 'double'.

Error in mptPolytope (line 61)
        obj.P=polytope(varargin{1},varargin{2});

Error in zonotope/polytope (line 101)
    P=mptPolytope([C;-C],[dPos;dNeg]);

Error in zonotopeBundle/polytope (line 34)
    Ptmp{i}=polytope(Zbundle.Z{i},varargin{2:end});

Error in deleteRedundantSets (line 54)
        R.P{i}=polytope(R.tp{i}.set,options);

Error in nonlinearSys/post (line 47)
Rnext = deleteRedundantSets(Rnext,R,options);

Error in contDynamics/reach (line 127)
    [Rnext,options]=post(obj,Rnext,options);

Error in example_nonlinear_reach_03_vanDerPol (line 80)
Rcont = reach(vanderPol, options);

**Comment by wetzlingerm** [comment]
To our knowledge, similar error stacks occur if the MPT toolbox is not installed, see Chapter 3 "Installation" in the CORA Manual 2018. Is the MPT toolbox installed?

If so and the error still occurs, please run the unit tests. If any further problems occur, please notify us here below.
